apiVersion: v1
kind: ConfigMap
metadata:
  name: moonly-pool-config-admin
data:
  CONNECTION_STRING: "Data Source=192.168.88.1:1433;Database=MoonlyBirdPoll;Integrated Security=false;User ID=sa;Encrypt=true;TrustServerCertificate=true"