apiVersion: v1
kind: Service
metadata:
  name: moonly-poll-api-service
  labels:
    app: moonly-poll
spec:
  selector:
    app: moonly-poll
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP